version: "2"

services:
  plone:
    image: eeacms/plone-emrt:11.3-1.0.3
    ports:
    - "8080:8080"
    volumes:
    - ./src:/plone/instance/src
    - ./data/filestorage:/data/filestorage
    - ./data/blobstorage:/data/blobstorage
    entrypoint: sh -c "tail -f /dev/null"

  memcached:
    image: memcached:1.4.37
    command:
    - -m
    - '2048'
